# LLM model configuration
# Copy this file to config/model_config.yaml and fill in your real API keys

models:
 "<model-name-1 here>": 
   api_type: "openai"
   base_url: "<your base url here>"
   api_key: "<your api key here>"
 "<model-name-2 here>": 
   api_type: "openai"
   base_url: "<your base url here>"
   api_key: "<your api key here>"